@startuml
'https://plantuml.com/sequence-diagram

autonumber
Actor Customer as Customer
Customer -> SearchController: SearchRequest
SearchController -> SearchService: SearchRequest
SearchService -> SearchDAO: SearchRequest

SearchDAO -> SearchService : SearchResponse
SearchService -> SearchController : SearchResponse
SearchController ->  Customer: SearchResponse
@enduml